spring:
  config:
    activate:
      on-profile: test
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true  # H2 콘솔 활성화

  jpa:
    hibernate:
      ddl-auto: create  # 테이블 자동 생성 설정