version: "3.7"

services:
  mariadb:
    image: mariadb:10.5.5
    init: true
    user: root
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./conf/data:/var/lib/mysql
      - ./conf/config:/etc/mysql/conf.d
    ports:
      - 3306:3306
    env_file: .env
    environment:
      TZ: Asia/Seoul